### ISSUE TITLE
codecov testing report

### ISSUE THREAD

**Issue by ClaudioZandonella** [ekothe/trackdown#10]
Dear @ekothe,

All unit tests are ready and the package has a ~96% of coverage.

There is only one thing that does not work properly. Github action evaluating test coverage runs correctly. However, it is not able to upload the report to codecov, so we miss the badge with the percentage.

I do not understand why. Maybe is something related to the rename of the repository as it says "Could not find a repository, try using upload token" [GitHub-action-link](https://github.com/ekothe/trackdown/runs/2533553886?check_suite_focus=true#step:9:14). Could you please try to follow these instructions at <https://docs.codecov.io/docs/quick-start#basic-usage>?

In particular, check please if the repo ekothe/trackdown is available and in case send me by email (claudiozandonella@gmail.com) the secret token as shown in the figure

It is strange as for public repo token is not required, but something is not working properly.

Thanks

**Comment by ekothe** [comment]
I believe that this is now working as intended - the README for the develop branch now has a codecov badge that shows the coverage percentage.
