### ISSUE TITLE
Google Team Drives are now Google Drive shared drives

### ISSUE THREAD

**Issue by januz** [ekothe/trackdown#15]
Google Team Drives have been rebranded as Google Drive shared drives. Accordingly, all functions in the `googledrive` package will  use that terminology from  2.0.0 on: https://googledrive.tidyverse.org/news/index.html

While the `team_drive` function arguments and the `team_drive_get()` function  I used to fix the team drive functionality should still work (at least for a while), we should plan for adapting our package once `googledrive` 2.0.0 is on CRAN. This will involve renaming all function arguments in our package and where we use `googledrive` functions.

I actually started implementing these changes in the feature branch but then 
stopped myself as I didn't want to make `trackdown` depend on a Github version of `googledrive`. As an intermediate strategy, we could already  rename all function arguments (and related documentation) in our package but keep them in the calls to `googledrive` functions. Maybe this would make it easier for users as we wouldn't have to rename an argument relatively soon after releasing `trackdown`. What do you think?

**Comment by Lingtax** [comment]
I'm not sure I'm following as I've not actually looked under the hood of the package in a while, but if I am, I think it's best from a user perspective to make the changes as minimal as possible moving forward. i.e. change all the arguments and documentation to anticipate the future changes in `googledrive` now, wait until `googledrive` 2.0 hits CRAN before moving the function calls to the new `shared_drive_get()` function.

**Comment by januz** [comment]
Yes, that would be my preference as well.

**Comment by ClaudioZandonella** [comment]
I agree with your suggestions arguments and documentation should follow current terms used by Google and anticipate the future changes in `googledrive` package...when `googledrive` 2.0 will is available we can change internal functions as well and specify the`googledrive` 2.0 version  as dependency

**Comment by januz** [comment]
Great, I just pushed these changes to the feature branch. Please make sure I did not forget anything (and didn't break the code :))

**Comment by ClaudioZandonella** [comment]
thanks @januz for all the changes...everything is perfect! I have merged all changes into the develop branch and then I merged the develop branch into the master branch so everything should be updated.  

I can close this issue now! We will wait for `googledrive` 2.0 version  to update internal functions👍
