### ISSUE TITLE
Cannot upload file

### ISSUE THREAD

**Issue by carlosyanez** [ekothe/trackdown#16]
Hi,
Thanks for developing this package.
I'm trying to upload a document for the first time, however tracdown seems to get stuck in the authentication stage: all what I get in the console after selecting my account is: "Auto-refreshing stale OAuth token".

Am I missing any dependencies. I'm running R 4.1.0 on Macos. The command I'm using is quite standard, I.e.::
upload_file(filename,
            gpath=google_path,
            hide_code=TRUE)

Thanks!
Carlos

**Comment by carlosyanez** [comment]
Sorry.this is a non issue. I added the full file path for the End file and it's working

**Comment by januz** [comment]
Glad you figured it out and hope you find our package useful! Is there any way in which you felt the documentation was misleading that we might want to adjust? Thanks

**Comment by carlosyanez** [comment]
I think the documentation is straightforward. 

I was assuming though it would work without the full path, as I was running it from within the project and my .Rmd was in the project's root. It could be down to my particular setup, so I will see if the error replicates on the other computer in the house and I'll report back if that helps.
