### ISSUE TITLE
trackdown githubpages

### ISSUE THREAD

**Issue by ClaudioZandonella** [ekothe/trackdown#9]
Dear @ekothe,

I have created a branch `gh-pages` with the rendered documentation of the package obtained with `pkgdown` package [documentation-link](https://pkgdown.r-lib.org/).

Could you please publish the GitHub pages following these instructions?

[Configuring a publishing source for your GitHub Pages site](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site)

In particular select:

- `gh-pages` as branch 
- `/(root)` as folder

The website should be automatically published at <https://ekothe.github.io/trackdown/>

Thanks!

**Comment by ekothe** [comment]
Thanks @ClaudioZandonella this is now building correctly and is visible at https://ekothe.github.io/trackdown/

**Comment by Lingtax** [comment]
@ekothe you might want to put the link to this on the main trackdown github repo page to increase discoverability. I tried just now and the option doesn't appear for me.
